/* Find all search details where data is missing from the host_response_rate column.
id	price	property_type	room_type	amenities	accommodates	bathrooms	bed_type	cancellation_policy	cleaning_fee	city	host_identity_verified	host_response_rate	host_since	neighbourhood	number_of_reviews	review_scores_rating	zipcode	bedrooms	beds
12513361	555.68	Apartment	Entire home/apt	{TV,"Wireless Internet","Air conditioning","Smoke detector","Carbon monoxide detector",Essentials,"Lock on bedroom door",Hangers,Iron}	2	1	Real Bed	flexible	0	NYC	t	89%	2015-11-18	East Harlem	3	87	10029	0	1
7196412	366.36	Cabin	Private room	{"Wireless Internet",Kitchen,Washer,Dryer,"Smoke detector","First aid kit","Fire extinguisher",Essentials,"Hair dryer","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}	2	3	Real Bed	moderate	0	LA	f	100%	2016-09-10	Valley Glen	14	91	91606	1	1
16333776	482.83	House	Private room	{TV,"Cable TV",Internet,"Wireless Internet",Kitchen,"Free parking on premises","Pets live on this property",Dog(s),"Indoor fireplace","Buzzer/wireless intercom",Heating,Washer,Dryer,"Smoke detector","Carbon monoxide detector","First aid kit","Safety card","Fire extinguisher",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50","Self Check-In",Lockbox}	2	1	Real Bed	strict	1	SF	t	100%	2013-12-26	Richmond District	117	96	94118	1	1
1786412	448.86	Apartment	Private room	{"Wireless Internet","Air conditioning",Kitchen,Heating,"Suitable for events","Smoke detector","Carbon monoxide detector","First aid kit","Fire extinguisher",Essentials,Shampoo,"Lock on bedroom door",Hangers,"translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}	2	1	Real Bed	strict	1	NYC	t	93%	2010-05-11	Williamsburg	8	86	11211	1	1
14575777	506.89	Villa	Private room	{TV,Internet,"Wireless Internet","Air conditioning",Kitchen,"Free parking on premises",Essentials,Shampoo,"translation missing: en.hosting_amenity_49","translation missing: en.hosting_amenity_50"}	6	2	Real Bed	strict	1	LA	t	70%	2015-10-22		2	100	90703	3	3
20515889	720.79	Villa	Entire home/apt	{TV,"Cable TV",Internet,"Wireless Internet",Kitchen,"Free parking on premises","Pets allowed","Elevator in building","Hot tub","Indoor fireplace",Heating,"Family/kid friendly","Suitable for events",Washer,Dryer,"Smoke detector","Carbon monoxide detector","First aid kit","Safety card","Fire extinguisher",Essentials,Shampoo}	8	3	Real Bed	strict	1	LA	f	20%	2014-05-26	Topanga	0		90265	3	4
13783491	516.48	Villa	Private room	{TV,"Cable TV",Internet,"Wireless Internet","Air conditioning",Pool,Kitchen,"Free parking on premises","Pets allowed","Hot tub","Indoor fireplace",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Shampoo,"Lock on bedroom door","24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace"}	2	1	Real Bed	strict	1	LA	t	90%	2015-08-20	Hollywood Hills	1	100	90046	1	1
6591755	529.33	Villa	Entire home/apt	{TV,"Cable TV",Internet,"Wireless Internet",Kitchen,"Pets allowed","Pets live on this property","Buzzer/wireless intercom",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Hangers,"Hair dryer",Iron,"Laptop friendly workspace"}	16	3	Real Bed	strict	1	LA	t	91%	2016-01-16	Long Beach	88	90	90803	4	6
5203241	679.68	Villa	Entire home/apt	{TV,"Cable TV",Internet,"Wireless Internet","Air conditioning",Pool,Kitchen,Gym,"Hot tub","Indoor fireplace",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector","Fire extinguisher",Essentials,Shampoo,"24-hour check-in",Hangers,"Hair dryer",Iron,"Laptop friendly workspace"}	6	2	Real Bed	strict	1	LA	t	100%	2017-08-17	Rancho Palos Verdes	1	100	90275	2	4
11508891	633.51	Villa	Entire home/apt	{TV,Internet,"Wireless Internet",Kitchen,"Free parking on premises",Heating,"Family/kid friendly",Washer,Dryer,Essentials,"24-hour check-in","Laptop friendly workspace","Self Check-In",Keypad}	10	2	Real Bed	strict	1	LA	t	94%	2015-08-12	Malibu	43	92	90265	2	2
18823930	485.98	Villa	Entire home/apt	{TV,Internet,"Wireless Internet",Kitchen,"Free parking on premises","Smoking allowed","Pets allowed",Heating,"Family/kid friendly",Washer,Dryer,Essentials,"24-hour check-in",Hangers,Iron,"Laptop friendly workspace"}	6	1	Real Bed	moderate	1	LA	t	90%	2013-12-06	Harbor Gateway	27	93	90501	2	2
15523281	598.9	Villa	Entire home/apt	{TV,"Cable TV",Internet,"Wireless Internet",Pool,Kitchen,"Free parking on premises",Gym,Breakfast,"Hot tub","Indoor fireplace",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"Lock on bedroom door",Hangers,"Private entrance"}	4	1	Real Bed	strict	1	LA	f	100%	2014-05-20		5	88	90704	1	2
19698509	741.76	Villa	Entire home/apt	{TV,"Cable TV",Internet,"Wireless Internet","Air conditioning",Kitchen,"Free parking on premises",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector","First aid kit","Safety card","Fire extinguisher",Essentials,Shampoo,Hangers,"Hair dryer",Iron}	8	4	Real Bed	super_strict_60	1	LA	t	100%	2015-01-05		0		90277	4	4
12497464	431.75	Apartment	Private room	{"Wireless Internet",Kitchen,"Buzzer/wireless intercom",Heating,"Family/kid friendly",Washer,Dryer,"Smoke detector","Carbon monoxide detector"}	2	1	Real Bed	moderate	1	NYC	t		2014-01-14	Crown Heights	2	80	11238	1	1
17764793	469.13	Villa	Private room	{TV,"Cable TV",Internet,"Wireless Internet","Air conditioning",Pool,"Pets live on this property",Dog(s),"Free parking on street","Hot tub",Heating,"Family/kid friendly","Smoke detector","Carbon monoxide detector",Essentials,Shampoo,"Lock on bedroom door",Hangers,"Hair dryer",Iron,"Laptop friendly workspace","translation missing: en.hosting_amenity_50"}	2	1	Real Bed	moderate	1	LA	t	100%	2012-11-02	Topanga	6	100	91364	1	1
*/
select *
from airbnb_search_details
where host_response_rate is null;